language: node_js
node_js: 
 - "stable"
stages:
  - security
services:
  - docker
# gitleaks:
#   stage: security
#   image: 
#     name: "zricethezav/gitleaks:v3.0.3"
#     entrypoint: [""] 
script:
 - npm init --yes
before_install:
 - npm install express@4.17.1
 - npm install express-session@1.17.1
 - npm install mysql@2.18.1
 - docker pull zricethezav/gitleaks
# - docker run --rm --name=gitleaks zricethezav/gitleaks --files-at-commit=$TRAVIS_COMMIT -v -r https://github.com/andrew-js-wright/security-reference-architecture --pretty
 - docker run --rm --name=gitleaks zricethezav/gitleaks --files-at-commit=$TRAVIS_COMMIT --pretty -v -r https://github.com/andrew-js-wright/security-reference-architecture
